"""empty message

Revision ID: 6df72f51065b
Revises: 729c6e376981
Create Date: 2020-04-04 13:26:26.577391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df72f51065b'
down_revision = '729c6e376981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('books', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'title')
    # ### end Alembic commands ###
