"""empty message

Revision ID: 729c6e376981
Revises: 
Create Date: 2020-04-02 22:58:22.734254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729c6e376981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
