"""empty message

Revision ID: ceb3da3643cf
Revises: 99cb0e58e1b3
Create Date: 2020-04-04 23:07:50.333706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb3da3643cf'
down_revision = '99cb0e58e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_authors', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('book_genres', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('book_shelves', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_shelves', 'id')
    op.drop_column('book_genres', 'id')
    op.drop_column('book_authors', 'id')
    # ### end Alembic commands ###
