"""empty message

Revision ID: e01097823b77
Revises: 99cb0e58e1b3
Create Date: 2020-04-09 19:15:50.462798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01097823b77'
down_revision = '99cb0e58e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('books', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'summary')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'image_url')
    # ### end Alembic commands ###
