"""empty message

Revision ID: f59affce270b
Revises: ceb3da3643cf
Create Date: 2020-04-04 23:47:07.723701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59affce270b'
down_revision = 'ceb3da3643cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_authors', 'id')
    op.drop_column('book_genres', 'id')
    op.drop_column('book_shelves', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_shelves', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('book_genres', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('book_authors', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
